//
// Quantum Script
//
// Copyright (c) 2020 Grigore Stefan <g_stefan@yahoo.com>
// Created by Grigore Stefan <g_stefan@yahoo.com>
//
// MIT License (MIT) <http://opensource.org/licenses/MIT>
//

#ifndef QUANTUM_SCRIPT_INSTRUCTION_HPP
#define QUANTUM_SCRIPT_INSTRUCTION_HPP

#ifndef QUANTUM_SCRIPT_INSTRUCTIONCONTEXT_HPP
#include "quantum-script-instructioncontext.hpp"
#endif

#ifndef QUANTUM_SCRIPT_INSTRUCTIONX_HPP
#include "quantum-script-instructionx.hpp"
#endif

namespace Quantum {
	namespace Script {

		using namespace XYO;

#define QUANTUM_SCRIPT_INSTRUCTION_DEFINE(Name) \
	void Instruction##Name(InstructionContext *context,Variable *operand)

#define QUANTUM_SCRIPT_INSTRUCTION_IMPLEMENT(Name) \
	void Instruction##Name(InstructionContext *context,Variable *operand)

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushUndefined);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushBoolean);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushNumber);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssign);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignPlus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignMinus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignMul);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignDiv);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignMod);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseOr);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseAnd);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseLeftShift);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseRightShift);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseRightShiftZero);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignBitwiseXor);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorEqual);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorEqualStrict);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorPlus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMinus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorUnaryPlus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMul);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorDiv);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMod);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorNotEqual);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorNotEqualStrict);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorNot);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorLessOrEqual);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorLess);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorGreaterOrEqual);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorGreater);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorLogicalOr);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseOr);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorLogicalAnd);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseAnd);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseNot);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseLeftShift);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseRightShift);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseRightShiftZero);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorBitwiseXor);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorIn);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmNop);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmMark);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmEnterContext);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLeaveContext);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmBreak);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContinue);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorEqual1);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPop1);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushNull);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmReturn);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmThrow);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetThis);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextPushThis);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushNewObject);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushString);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfFalseGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetBreak);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetContinue);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfTrueGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXPushFunction);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetCatch);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetFinally);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetTryBreak);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetTryContinue);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetTryReturn);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetTryThrow);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmEnterFirstContext);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmAssign);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmCallNative);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushNewArray);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmArrayPush);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorArrayPush);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmReferenceObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorInstanceOf);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorTypeOf);


		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorReferenceReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorArrayPushReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorObjectReferenceValue);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorPlusPlusLeft);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorPlusPlusRight);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMinusMinusLeft);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMinusMinusRight);


		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXPushNewArray);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXArrayPushWithTransfer);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCall);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCallSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCallThis);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCallThisModeCall);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCallThisModeApply);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXCallWithThisReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmAssignReverse);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmDuplicate);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorAssignXPrototype);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmArgumentsPushObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmArgumentsPushSymbol);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmAssignNewObject);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmCatch);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmArgumentsLevelPushObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmArgumentsLevelPushSymbol);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLocalVariablesPushObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLocalVariablesPushSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLocalVariablesLevelPushObjectReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLocalVariablesLevelPushSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmEndExecution);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfArgumentsSymbolNotEqualNumberGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMinusArgumentsSymbolXNumber);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmSymbolPlusPlus);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfSymbolNotLessNumberGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfArgumentsSymbolNotLessNumberGoto);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmYield);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetReference);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorSetReferenceIndexKey);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorNextReferenceIndex);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorSetReferenceIndexValue);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetRegisterValue);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextPushRegisterValue);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMulLocalVariablesSymbol2);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorMinusLocalVariablesSymbol2);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorPlusLocalVariablesSymbol2);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextPushSelf);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmCurrentContextExit);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushArguments);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmSetFunction);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmIfNotGreaterGoto);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXPushFunctionActive);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmInstructionListExtractAndDelete);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorReferenceDeleteIndex);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorReferenceDeleteReference);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetStack);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmClearIncludedFile);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmOperatorPow2LocalVariablesSymbol);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCall);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCallSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCallThis);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCallThisModeCall);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCallThisModeApply);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmXTailCallWithThisReference);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmAssignLocalVariablesObjectReferencePow2LocalVariablesSymbol);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmLocalVariablesPlusPlus);

		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmPushGlobal);
		QUANTUM_SCRIPT_EXPORT QUANTUM_SCRIPT_INSTRUCTION_DEFINE(VmContextSetPC);

	};
};


#endif
